//
// Copyright (c) 2019 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

loadGlobalLibrary()

def image_amd64
def changeDetected

pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }
    stages {
        stage('LF Prep') {
            steps {
                edgeXSetupEnvironment()

                script {
                    changeDetected = edgex.didChange('sonarqube')
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    image_amd64 = docker.build('edgex-sonarqube', '-f sonarqube/Dockerfile ./sonarqube')
                }
            }
        }
    }

}
