run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 120s

issues:
  exclude-files:
    - doc.go

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - unparam
    - unconvert
    - misspell
    - goconst
  disable:
    - gosimple
