version: "2"

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 120s

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - unparam
    - unconvert
    - misspell
    - goconst
  paths:
    - doc.go
